package br.upe.greenroute.view.gui;

import br.upe.greenroute.model.*;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

public class MainView extends JFrame implements IMainGui {
    private JPanel mainPanel;
    private JTabbedPane tabbedPane1;
    private JTable cityTable;
    private JButton btnAddCity;
    private JButton btnUpdCity;
    private JButton btnDelCity;
    private JComboBox cbSearchCity;
    private JTextField txtCitySearchInput;
    private JButton btnCityFilter;
    private JTable stationTable;
    private JButton btnDelStation;
    private JButton btnAddStation;
    private JButton btnUpdStation;
    private JComboBox cbSearchStation;
    private JButton btnStationFilter;
    private JTextField txtStationSearchInput;
    private JTable vehicleTable;
    private JButton btnUpdVehicle;
    private JButton btnDelVehicle;
    private JButton btnAddVehicle;
    private JTextField txtVehicleSearchInput;
    private JButton btnVehicleFilter;
    private JComboBox cbSearchVehicle;
    private JButton btnFastAddCity;
    private JButton btnFastAddStation;
    private JButton btnFastAddVehicle;
    private JButton btnGenerateRoute;
    private JLabel lblselectedVehicle;
    private JLabel lblSelectedCity;

    public MainView() {
        $$$setupUI$$$();
        setTitle("GreenRoute");
        setContentPane(mainPanel);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(800, 600);
        setLocationRelativeTo(null);
        cbSearchCity.addActionListener(e -> {
            boolean showCityFields = !cbSearchCity.getSelectedItem().toString().equals("Todos");
            txtCitySearchInput.setVisible(showCityFields);
            btnCityFilter.setVisible(showCityFields);
            if (showCityFields) txtCitySearchInput.setText("");
        });
        cbSearchStation.addActionListener(e -> {
            boolean showStationFields = !cbSearchStation.getSelectedItem().toString().equals("Todos");
            txtStationSearchInput.setVisible(showStationFields);
            btnStationFilter.setVisible(showStationFields);
            if (showStationFields) txtStationSearchInput.setText("");
        });
        cbSearchVehicle.addActionListener(e -> {
            boolean showVehicleFields = !cbSearchVehicle.getSelectedItem().toString().equals("Todos");
            txtVehicleSearchInput.setVisible(showVehicleFields);
            btnVehicleFilter.setVisible(showVehicleFields);
            if (showVehicleFields) txtVehicleSearchInput.setText("");
        });
        txtCitySearchInput.setVisible(false);
        btnCityFilter.setVisible(false);
        txtStationSearchInput.setVisible(false);
        btnStationFilter.setVisible(false);
        txtVehicleSearchInput.setVisible(false);
        btnVehicleFilter.setVisible(false);
        setupTableListeners();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1 = new JTabbedPane();
        mainPanel.add(tabbedPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(4, 4, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("Cidades", panel1);
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, new GridConstraints(1, 0, 3, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        cityTable = new JTable();
        scrollPane1.setViewportView(cityTable);
        btnUpdCity = new JButton();
        btnUpdCity.setText("Atualizar");
        panel1.add(btnUpdCity, new GridConstraints(2, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnDelCity = new JButton();
        btnDelCity.setText("Excluir");
        panel1.add(btnDelCity, new GridConstraints(3, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnAddCity = new JButton();
        btnAddCity.setText("Adicionar");
        panel1.add(btnAddCity, new GridConstraints(1, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cbSearchCity = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Todos");
        defaultComboBoxModel1.addElement("ID");
        defaultComboBoxModel1.addElement("Estado (UF)");
        cbSearchCity.setModel(defaultComboBoxModel1);
        cbSearchCity.setToolTipText("");
        panel1.add(cbSearchCity, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnCityFilter = new JButton();
        btnCityFilter.setText("Filtrar");
        panel1.add(btnCityFilter, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtCitySearchInput = new JTextField();
        txtCitySearchInput.setText("");
        panel1.add(txtCitySearchInput, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        btnFastAddCity = new JButton();
        btnFastAddCity.setText("Adição Rápida");
        panel1.add(btnFastAddCity, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(4, 4, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("Eletropostos", panel2);
        final JScrollPane scrollPane2 = new JScrollPane();
        panel2.add(scrollPane2, new GridConstraints(1, 0, 3, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        stationTable = new JTable();
        scrollPane2.setViewportView(stationTable);
        btnDelStation = new JButton();
        btnDelStation.setText("Excluir");
        panel2.add(btnDelStation, new GridConstraints(3, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnAddStation = new JButton();
        btnAddStation.setText("Adicionar");
        panel2.add(btnAddStation, new GridConstraints(1, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnUpdStation = new JButton();
        btnUpdStation.setText("Atualizar");
        panel2.add(btnUpdStation, new GridConstraints(2, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cbSearchStation = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
        defaultComboBoxModel2.addElement("Todos");
        defaultComboBoxModel2.addElement("ID");
        defaultComboBoxModel2.addElement("Cidade");
        cbSearchStation.setModel(defaultComboBoxModel2);
        panel2.add(cbSearchStation, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnStationFilter = new JButton();
        btnStationFilter.setText("Filtrar");
        panel2.add(btnStationFilter, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtStationSearchInput = new JTextField();
        panel2.add(txtStationSearchInput, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        btnFastAddStation = new JButton();
        btnFastAddStation.setText("Adição Rápida");
        panel2.add(btnFastAddStation, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(4, 4, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("Veículos", panel3);
        btnVehicleFilter = new JButton();
        btnVehicleFilter.setText("Filtrar");
        panel3.add(btnVehicleFilter, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane3 = new JScrollPane();
        panel3.add(scrollPane3, new GridConstraints(1, 0, 3, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        vehicleTable = new JTable();
        scrollPane3.setViewportView(vehicleTable);
        txtVehicleSearchInput = new JTextField();
        panel3.add(txtVehicleSearchInput, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        cbSearchVehicle = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel3 = new DefaultComboBoxModel();
        defaultComboBoxModel3.addElement("Todos");
        defaultComboBoxModel3.addElement("ID");
        cbSearchVehicle.setModel(defaultComboBoxModel3);
        panel3.add(cbSearchVehicle, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnDelVehicle = new JButton();
        btnDelVehicle.setText("Excluir");
        panel3.add(btnDelVehicle, new GridConstraints(3, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnAddVehicle = new JButton();
        btnAddVehicle.setText("adicionar");
        panel3.add(btnAddVehicle, new GridConstraints(1, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnUpdVehicle = new JButton();
        btnUpdVehicle.setText("atualizar");
        panel3.add(btnUpdVehicle, new GridConstraints(2, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnFastAddVehicle = new JButton();
        btnFastAddVehicle.setText("Adição Rápida");
        panel3.add(btnFastAddVehicle, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridLayoutManager(6, 5, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("Planejar Viagem", panel4);
        btnGenerateRoute = new JButton();
        btnGenerateRoute.setText("Gerar Rota");
        panel4.add(btnGenerateRoute, new GridConstraints(4, 1, 1, 3, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("\"Para planejar uma viagem selecione um veiculo na aba \"Veículos\" e uma cidade na aba \"Cidades!\"");
        panel4.add(label1, new GridConstraints(3, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel4.add(spacer1, new GridConstraints(5, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        lblselectedVehicle = new JLabel();
        var line = BorderFactory.createLineBorder(Color.GRAY, 1);
        var space = BorderFactory.createEmptyBorder(10, 15, 10, 15);
        lblselectedVehicle.setBorder(BorderFactory.createCompoundBorder(line, space));
        lblselectedVehicle.setBackground(new Color(-1));
        lblselectedVehicle.setForeground(new Color(-16777216));
        lblselectedVehicle.setOpaque(false);
        lblselectedVehicle.setText("Nenhum veículo selecionado");
        panel4.add(lblselectedVehicle, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblSelectedCity = new JLabel();
        lblSelectedCity.setBorder(BorderFactory.createCompoundBorder(line, space));
        lblSelectedCity.setForeground(new Color(-16777216));
        lblSelectedCity.setText("Nenhuma cidade selecionada");
        panel4.add(lblSelectedCity, new GridConstraints(1, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel4.add(spacer2, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        panel4.add(spacer3, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer4 = new Spacer();
        panel4.add(spacer4, new GridConstraints(2, 0, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer5 = new Spacer();
        panel4.add(spacer5, new GridConstraints(2, 4, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }


    @Override
    public void errorMessage(String message) {
        JOptionPane.showMessageDialog(this, message, "Erro", JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public void successMessage(String message) {
        JOptionPane.showMessageDialog(this, message, "Sucesso", JOptionPane.INFORMATION_MESSAGE);
    }

    @Override
    public String getSearchType() {
        int currentTab = tabbedPane1.getSelectedIndex();
        switch (currentTab) {
            case 0 -> {
                return cbSearchCity.getSelectedItem().toString();
            }
            case 1 -> {
                return cbSearchStation.getSelectedItem().toString();
            }
            case 2 -> {
                return cbSearchVehicle.getSelectedItem().toString();
            }
            default -> {
                return "Todos";
            }
        }
    }

    @Override
    public String getSearchInput() {
        int currentTab = tabbedPane1.getSelectedIndex();
        switch (currentTab) {
            case 0 -> {
                return txtCitySearchInput.getText().trim();
            }
            case 1 -> {
                return txtStationSearchInput.getText().trim();
            }
            case 2 -> {
                return txtVehicleSearchInput.getText().trim();
            }
            default -> {
                return "";
            }
        }
    }

    @Override
    public boolean confirmAction(String title, String message) {
        int choice = JOptionPane.showConfirmDialog(this, message, title, JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        return choice == JOptionPane.YES_OPTION;
    }

    @Override
    public int getSelectedItemRow() {
        int currentTab = tabbedPane1.getSelectedIndex();
        switch (currentTab) {
            case 0 -> {
                return cityTable.getSelectedRow();
            }
            case 1 -> {
                return stationTable.getSelectedRow();
            }
            case 2 -> {
                return vehicleTable.getSelectedRow();
            }
        }
        return -1;
    }

    @Override
    public int getSelectedItemId() {
        int currentTab = tabbedPane1.getSelectedIndex();
        int row = getSelectedItemRow();
        switch (currentTab) {
            case 0:
                if (row != -1) {
                    return (int) cityTable.getValueAt(row, 0);
                }
                break;
            case 1:
                if (row != -1) {
                    return (int) stationTable.getValueAt(row, 0);
                }
                break;
            case 2:
                if (row != -1) {
                    return (int) vehicleTable.getValueAt(row, 0);
                }
        }
        return -1;
    }

    @Override
    public void updateCityTable(List<CityModel> cities) {
        String[] columns = {"ID", "Nome", "Estado", "Distância da Capital (Km)"};
        DefaultTableModel model = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        for (CityModel city : cities) {
            Object[] lines = {
                    city.getId(),
                    city.getName(),
                    city.getState(),
                    city.getCapitalDistance()
            };
            model.addRow(lines);
        }
        cityTable.setModel(model);
    }

    @Override
    public String[] showCityFormDialog(String[] existingData) {
        CityFormDialog dialog = new CityFormDialog(this);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        if (existingData != null) {
            dialog.setTitle("Atualizar Cidade");
            dialog.setCityData(existingData[0], existingData[1], existingData[2]);
        } else {
            dialog.setTitle("Adicionar Cidade");
        }
        dialog.setVisible(true);
        if (dialog.isConfirmed()) {
            return dialog.getCityInputs();
        }
        return null;
    }

    public JButton getBtnAddCity() {
        return btnAddCity;
    }

    public JButton getBtnUpdtCity() {
        return btnUpdCity;
    }

    public JButton getBtnDelCity() {
        return btnDelCity;
    }

    public JButton getBtnCityFilter() {
        return btnCityFilter;
    }

    public JComboBox<String> getCbSearchCity() {
        return cbSearchCity;
    }

    @Override
    public void updateStationTable(List<ChargingStationModel> stations) {
        String[] columns = {"ID", "Nome", "Localização", "Cidade ID", "Conectores", "pôtencia (Kw)", "Preço (Kwh)", "Vagas"};
        DefaultTableModel model = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        for (ChargingStationModel station : stations) {
            String connectors = String.join(",", station.getAvailableConnectorsType());
            Object[] lines = {
                    station.getId(),
                    station.getName(),
                    station.getLocation(),
                    station.getCityId(),
                    connectors,
                    station.getChargingPowerKW(),
                    station.getPricePerKWh(),
                    station.getAvailableVacancies()
            };
            model.addRow(lines);
        }
        stationTable.setModel(model);
    }

    @Override
    public String[] showStationFormDialog(String[] existingData) {
        StationFormDialog dialog = new StationFormDialog(this);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        if (existingData != null) {
            dialog.setTitle("Atualizar Eletroposto");
            dialog.setStationData(existingData[0], existingData[1], existingData[2], existingData[3], existingData[4], existingData[5], existingData[6]);
            dialog.lockCityIdField();
        } else {
            dialog.setTitle("Adicionar Eletroposto");
        }
        dialog.setVisible(true);
        if (dialog.isConfirmed()) {
            return dialog.getStationInputs();
        }
        return null;
    }

    public JButton getBtnAddStation() {
        return btnAddStation;
    }

    public JButton getBtnUpdStation() {
        return btnUpdStation;
    }

    public JButton getBtnDelStation() {
        return btnDelStation;
    }

    public JButton getBtnStationFilter() {
        return btnStationFilter;
    }

    public JComboBox<String> getCbSearchStation() {
        return cbSearchStation;
    }

    @Override
    public void updateVehicleTable(List<VehicleModel> vehicles) {
        String[] columns = {"ID", "Tipo", "Modelo", "Autonomia (MAX)", "Carga Atual", "Consumo (Kwh/Km)", "Tempo de Recarga", "Conector", "Tempo de Recarga (Alta Potência)", "Capacidade do tanque (l)", "Consumo de Combustível", "Tipo de Combustível"};
        DefaultTableModel model = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        for (VehicleModel vehicle : vehicles) {
            String type = "";
            String connectorType = "-";
            String fastCharging = "-";
            String fuelTankCapacity = "-";
            String fuelConsumption = "-";
            String fuelType = "-";
            if (vehicle instanceof ElectricVehicleModel ev) {
                type = "Elétrico";
                connectorType = ev.getConnectorType();
                fastCharging = String.valueOf(ev.getFastCharging());
            } else if (vehicle instanceof HybridVehicleModel hv) {
                type = "Híbrido";
                fuelTankCapacity = String.valueOf(hv.getFuelTankCapacity());
                fuelConsumption = String.valueOf(hv.getFuelConsumption());
                fuelType = hv.getFuelType();
            }
            Object[] lines = {
                    vehicle.getId(),
                    type,
                    vehicle.getModel(),
                    vehicle.getMaximumAutonomy(),
                    vehicle.getCurrentBatteryCharge(),
                    vehicle.getConsumeKwhPerKm(),
                    vehicle.getFullRechargeTime(),
                    connectorType, fastCharging, fuelTankCapacity, fuelConsumption, fuelType
            };
            model.addRow(lines);
        }
        vehicleTable.setModel(model);
    }

    @Override
    public String[] showVehicleFormDialog(String type, String[] existingData) {
        VehicleFormDialog dialog = new VehicleFormDialog(this);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        if (existingData != null) {
            dialog.setTitle("Atualizar Veículo");
            dialog.setVehicleData(type, existingData[0], existingData[1], existingData[2], existingData[3], existingData[4], existingData[5], existingData[6], existingData[7], existingData[8], existingData[9]);
            dialog.lockVehicleType();
        } else {
            dialog.setTitle("Adicionar Veículo");
            dialog.getCbVehicleType().setSelectedIndex(0);
        }
        dialog.setVisible(true);
        if (dialog.isConfirmed()) {
            return dialog.getVehicleInputs();
        }
        return null;
    }

    public JButton getBtnAddVehicle() {
        return btnAddVehicle;
    }

    public JButton getBtnUpdVehicle() {
        return btnUpdVehicle;
    }

    public JButton getBtnDelVehicle() {
        return btnDelVehicle;
    }

    public JButton getBtnVehicleFilter() {
        return btnVehicleFilter;
    }

    public JComboBox<String> getCbSearchVehicle() {
        return cbSearchVehicle;
    }

    @Override
    public String showAiDialog() {
        IAFormDialog dialog = new IAFormDialog(this);
        dialog.setSize(500, 400);
        dialog.setLocationRelativeTo(this);
        dialog.setTitle("Adição Rápida com IA");
        dialog.clearUserText();
        dialog.setVisible(true);
        if (dialog.isConfirmed()) {
            return dialog.getUserText();
        }
        return null;
    }

    public JButton getBtnFastAddCity() {
        return btnFastAddCity;
    }

    public JButton getBtnFastAddStation() {
        return btnFastAddStation;
    }

    public JButton getBtnFastAddVehicle() {
        return btnFastAddVehicle;
    }

    @Override
    public int getSelectedCityId() {
        int row = cityTable.getSelectedRow();
        if (row != -1) {
            return (int) cityTable.getValueAt(row, 0);
        }
        return -1;
    }

    @Override
    public int getSelectedVehicleId() {
        int row = vehicleTable.getSelectedRow();
        if (row != -1) {
            return (int) vehicleTable.getValueAt(row, 0);
        }
        return -1;
    }

    @Override
    public void showTripReportDialog(String report) {
        String finalReport = report.replace("*", "").replace("#", "");
        JTextArea textArea = new JTextArea(finalReport);
        textArea.setLineWrap(true);
        textArea.setWrapStyleWord(true);
        textArea.setEditable(false);
        textArea.setMargin(new Insets(10, 10, 10, 10));
        JScrollPane scrollPane = new JScrollPane(textArea);
        scrollPane.setPreferredSize(new Dimension(500, 400));
        JOptionPane.showMessageDialog(this, scrollPane, "Relatório de Viagem", JOptionPane.PLAIN_MESSAGE);
    }

    public JButton getBtnGenerateRoute() {
        return btnGenerateRoute;
    }

    private void setupTableListeners() {
        cityTable.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int selectedRow = cityTable.getSelectedRow();
                if (selectedRow != -1) {
                    String cityName = cityTable.getValueAt(selectedRow, 1).toString();
                    String cityState = cityTable.getValueAt(selectedRow, 2).toString();
                    lblSelectedCity.setText("Destino: " + cityName + " - " + cityState);
                } else {
                    lblSelectedCity.setText("\"Nenhuma cidade selecionada\"");
                }
            }
        });
        vehicleTable.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int selectedRow = vehicleTable.getSelectedRow();
                if (selectedRow != -1) {
                    String vehicleModel = vehicleTable.getValueAt(selectedRow, 2).toString();
                    lblselectedVehicle.setText("Veículo Escolhido: " + vehicleModel);
                } else {
                    lblselectedVehicle.setText("\"Nenhum veículo selecionado\"");
                }
            }
        });
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
}