package br.upe.greenroute.view.gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class VehicleFormDialog extends JDialog implements IVehicleGui{
    private JPanel contentPane;
    private JButton buttonOK;
    private JButton buttonCancel;
    private JTextField txtModel;
    private JTextField txtAutonomy;
    private JTextField txtCurrentBatery;
    private JTextField txtConsume;
    private JTextField txtRechargeTime;
    private JTextField txtConnector;
    private JTextField txtFastRechargeTime;
    private JTextField txtFuelCapacity;
    private JTextField txtFuelConsume;
    private JTextField txtFuelType;
    private JComboBox cbVehicleType;
    private JLabel vehicleModel;
    private JLabel vehicleAutonomy;
    private JLabel vehicleBatery;
    private JLabel vehicleConsume;
    private JLabel vehicleRechargeTime;
    private JLabel eVehicleConnectorType;
    private JLabel eVehicleFastRecharge;
    private JLabel hVehicleFuelTank;
    private JLabel hVehicleFuelConsume;
    private JLabel hVehicleFuelType;

    private boolean confirmed = false;

    public VehicleFormDialog(Frame parent) {
        super(parent, true);
        setContentPane(contentPane);
        setModal(true);
        getRootPane().setDefaultButton(buttonOK);
        setupComboBoxListener();

        buttonOK.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                onOK();
            }
        });

        buttonCancel.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                onCancel();
            }
        });

        // call onCancel() when cross is clicked
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                onCancel();
            }
        });

        // call onCancel() on ESCAPE
        contentPane.registerKeyboardAction(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                onCancel();
            }
        }, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
    }

    private void onOK() {
        // add your code here
        this.confirmed = true;
        dispose();
    }

    private void onCancel() {
        // add your code here if necessary
        this.confirmed = false;
        dispose();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(3, 1, new Insets(10, 10, 10, 10), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(panel1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, 1, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1, true, false));
        panel1.add(panel2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        buttonOK = new JButton();
        buttonOK.setText("OK");
        panel2.add(buttonOK, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        buttonCancel = new JButton();
        buttonCancel.setText("Cancel");
        panel2.add(buttonCancel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(10, 2, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(panel3, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        vehicleModel = new JLabel();
        vehicleModel.setText("Modelo:");
        panel3.add(vehicleModel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        vehicleAutonomy = new JLabel();
        vehicleAutonomy.setText("Autonomia Máxima:");
        panel3.add(vehicleAutonomy, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        hVehicleFuelType = new JLabel();
        hVehicleFuelType.setText("Tipo de Combustível:");
        panel3.add(hVehicleFuelType, new GridConstraints(9, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        vehicleBatery = new JLabel();
        vehicleBatery.setText("Carga Atual da Bateria:");
        panel3.add(vehicleBatery, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        vehicleConsume = new JLabel();
        vehicleConsume.setText("Consumo (Kwh por Km):");
        panel3.add(vehicleConsume, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        vehicleRechargeTime = new JLabel();
        vehicleRechargeTime.setText("Tempo de Recarga:");
        panel3.add(vehicleRechargeTime, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        eVehicleConnectorType = new JLabel();
        eVehicleConnectorType.setText("Tipo de Conector:");
        panel3.add(eVehicleConnectorType, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        eVehicleFastRecharge = new JLabel();
        eVehicleFastRecharge.setText("tempo de Recarga Rápida:");
        panel3.add(eVehicleFastRecharge, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        hVehicleFuelTank = new JLabel();
        hVehicleFuelTank.setText("Capacidade do Tanque (l):");
        panel3.add(hVehicleFuelTank, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        hVehicleFuelConsume = new JLabel();
        hVehicleFuelConsume.setText("Consumo de Combustivel (Km/l):");
        panel3.add(hVehicleFuelConsume, new GridConstraints(8, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtModel = new JTextField();
        panel3.add(txtModel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtAutonomy = new JTextField();
        txtAutonomy.setText("");
        panel3.add(txtAutonomy, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtCurrentBatery = new JTextField();
        txtCurrentBatery.setText("");
        panel3.add(txtCurrentBatery, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtConsume = new JTextField();
        panel3.add(txtConsume, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtRechargeTime = new JTextField();
        panel3.add(txtRechargeTime, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtConnector = new JTextField();
        panel3.add(txtConnector, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtFastRechargeTime = new JTextField();
        panel3.add(txtFastRechargeTime, new GridConstraints(6, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtFuelCapacity = new JTextField();
        panel3.add(txtFuelCapacity, new GridConstraints(7, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtFuelConsume = new JTextField();
        panel3.add(txtFuelConsume, new GridConstraints(8, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtFuelType = new JTextField();
        panel3.add(txtFuelType, new GridConstraints(9, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        cbVehicleType = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Elétrico");
        defaultComboBoxModel1.addElement("Híbrido");
        cbVehicleType.setModel(defaultComboBoxModel1);
        contentPane.add(cbVehicleType, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

    @Override
    public String[] getVehicleInputs() {
        return new String[] {
                cbVehicleType.getSelectedItem().toString(),
                txtModel.getText(),
                txtAutonomy.getText(),
                txtCurrentBatery.getText(),
                txtConsume.getText(),
                txtRechargeTime.getText(),
                txtConnector.getText(),
                txtFastRechargeTime.getText(),
                txtFuelCapacity.getText(),
                txtFuelConsume.getText(),
                txtFuelType.getText()
        };
    }
    @Override
    public boolean isConfirmed() {
        return this.confirmed;
    };

    @Override
    public void setVehicleData(String type, String model, String maximumAutonomy, String currentBatteryCharge, String consumptionKWhPerKm, String fullRechargeTime, String connectorType, String fastCharging, String fuelTankCapacity, String fuelConsumption, String fuelType) {
        if (type.equals("Elétrico") || type.equals("Híbrido")) {
            cbVehicleType.setSelectedItem(type);
        }
        txtModel.setText(model);
        txtAutonomy.setText(maximumAutonomy);
        txtCurrentBatery.setText(currentBatteryCharge);
        txtConsume.setText(consumptionKWhPerKm);
        txtRechargeTime.setText(fullRechargeTime);
        txtConnector.setText(connectorType);
        txtFastRechargeTime.setText(fastCharging);
        txtFuelCapacity.setText(fuelTankCapacity);
        txtFuelConsume.setText(fuelConsumption);
        txtFuelType.setText(fuelType);
    }
    public void lockVehicleType() {
        cbVehicleType.setEnabled(false);
    }
    public JComboBox getCbVehicleType() {
        return cbVehicleType;
    }
    private void setupComboBoxListener() {
        cbVehicleType.addActionListener( e -> updateFieldsVisibility());
        updateFieldsVisibility();
    }
    private void updateFieldsVisibility() {
        Object selected = cbVehicleType.getSelectedItem();
        if (selected == null) {
            return;
        }
        String selectedType = selected.toString();
        boolean isElectric = selectedType.equals("Elétrico");
        boolean isHybrid = selectedType.equals("Híbrido");
        hVehicleFuelTank.setVisible(isHybrid);
        txtFuelCapacity.setVisible(isHybrid);
        hVehicleFuelConsume.setVisible(isHybrid);
        txtFuelConsume.setVisible(isHybrid);
        hVehicleFuelType.setVisible(isHybrid);
        txtFuelType.setVisible(isHybrid);
        eVehicleConnectorType.setVisible(isElectric);
        txtConnector.setVisible(isElectric);
        eVehicleFastRecharge.setVisible(isElectric);
        txtFastRechargeTime.setVisible(isElectric);
        this.revalidate();
        this.repaint();
        this.pack();
    }
}
